import React, { useState, useEffect } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { useNotification } from '../../hooks/useNotification';
import { payrollService } from '../../services/payrollService';
import StatCard from '../../components/common/StatCard';
import Badge from '../../components/common/Badge';
import Modal from '../../components/common/Modal';
import LoadingSpinner from '../../components/common/LoadingSpinner';
import EmptyState from '../../components/common/EmptyState';
import { DollarSign, FileText, Download, Eye, CheckCircle2, ShieldAlert } from 'lucide-react';
import { formatDate, formatCurrency } from '../../utils/formatters';

export const EmployeePayroll = () => {
  const { user } = useAuth();
  const { addToast } = useNotification();

  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedPayslip, setSelectedPayslip] = useState(null);
  const [isDetailsModalOpen, setIsDetailsModalOpen] = useState(false);

  useEffect(() => {
    const loadPayslips = async () => {
      setLoading(true);
      try {
        const data = await payrollService.getMyPayslips();
        setPayslips(data);
      } catch (err) {
        console.error('Failed to load payslips:', err);
      } finally {
        setLoading(false);
      }
    };

    loadPayslips();
  }, []);

  const handleViewPayslip = (payslip) => {
    setSelectedPayslip(payslip);
    setIsDetailsModalOpen(true);
  };

  const handleDownload = (payslip) => {
    addToast(`Downloading payslip for ${payslip.pay_period}...`, 'info');
  };

  const latestSlip = payslips[0];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Header */}
      <div>
        <h1 style={{ fontSize: '1.65rem', fontWeight: 700 }}>Salary & Payslips (Read-Only)</h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>
          Confidential compensation statements, allowances breakdown, and tax deductions
        </p>
      </div>

      {/* Salary Overview Summary Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1rem' }}>
        <StatCard
          title="Monthly Net Take-Home"
          value={formatCurrency(latestSlip?.net_salary || 7430)}
          subtitle={latestSlip?.pay_period || 'August 2026'}
          icon={DollarSign}
          color="success"
        />
        <StatCard
          title="Basic Base Salary"
          value={formatCurrency(latestSlip?.base_salary || 7500)}
          subtitle="Fixed Monthly Base"
          icon={FileText}
          color="primary"
        />
        <StatCard
          title="Total Allowances"
          value={formatCurrency(latestSlip?.allowances || 850)}
          subtitle="HRA, Transport, Medical"
          icon={DollarSign}
          color="info"
        />
        <StatCard
          title="Total Deductions"
          value={formatCurrency(latestSlip?.deductions || 920)}
          subtitle="Tax & Healthcare withholding"
          icon={DollarSign}
          color="warning"
        />
      </div>

      {/* Payslips History Table Card */}
      <div className="card">
        <div style={{ marginBottom: '1.25rem' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 600 }}>Payslip Statements History</h3>
          <p style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>Archived compensation statements by pay period</p>
        </div>

        {loading ? (
          <LoadingSpinner message="Loading payslip history..." />
        ) : payslips.length === 0 ? (
          <EmptyState title="No payslips available" description="Payslips will appear here once generated by HR." />
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.875rem' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--border-subtle)', color: 'var(--text-dim)' }}>
                  <th style={{ padding: '0.75rem 1rem' }}>Pay Period</th>
                  <th style={{ padding: '0.75rem 1rem' }}>Gross Pay</th>
                  <th style={{ padding: '0.75rem 1rem' }}>Deductions</th>
                  <th style={{ padding: '0.75rem 1rem' }}>Net Salary</th>
                  <th style={{ padding: '0.75rem 1rem' }}>Payment Status</th>
                  <th style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {payslips.map((slip) => (
                  <tr key={slip.id} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 600, color: 'var(--text-main)' }}>
                      {slip.pay_period}
                    </td>
                    <td style={{ padding: '0.75rem 1rem', color: 'var(--text-muted)' }}>
                      {formatCurrency((slip.base_salary || 0) + (slip.allowances || 0))}
                    </td>
                    <td style={{ padding: '0.75rem 1rem', color: 'var(--danger)' }}>
                      -{formatCurrency(slip.deductions || 0)}
                    </td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--success)' }}>
                      {formatCurrency(slip.net_salary)}
                    </td>
                    <td style={{ padding: '0.75rem 1rem' }}>
                      <Badge status={slip.status} />
                    </td>
                    <td style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>
                      <div style={{ display: 'inline-flex', gap: '0.5rem' }}>
                        <button
                          onClick={() => handleViewPayslip(slip)}
                          className="btn btn-outline"
                          style={{ padding: '0.35rem 0.6rem', fontSize: '0.75rem' }}
                          title="View Breakdown"
                        >
                          <Eye size={14} /> View
                        </button>
                        <button
                          onClick={() => handleDownload(slip)}
                          className="btn btn-outline"
                          style={{ padding: '0.35rem 0.6rem', fontSize: '0.75rem' }}
                          title="Download PDF"
                        >
                          <Download size={14} /> PDF
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Payslip Details Breakdown Modal */}
      <Modal
        isOpen={isDetailsModalOpen}
        onClose={() => setIsDetailsModalOpen(false)}
        title={`Payslip Breakdown - ${selectedPayslip?.pay_period}`}
        maxWidth="600px"
      >
        {selectedPayslip && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {/* Header info */}
            <div style={{ padding: '0.75rem', backgroundColor: 'var(--bg-main)', borderRadius: 'var(--radius-sm)', display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
              <div>
                <span style={{ color: 'var(--text-dim)', display: 'block' }}>Employee Name</span>
                <strong>{selectedPayslip.employee_name}</strong>
              </div>
              <div>
                <span style={{ color: 'var(--text-dim)', display: 'block' }}>Payment Status</span>
                <Badge status={selectedPayslip.status} />
              </div>
            </div>

            {/* Breakdown List */}
            <div>
              <h4 style={{ fontSize: '0.9rem', fontWeight: 600, marginBottom: '0.75rem' }}>Earnings & Deductions Itemized</h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                {selectedPayslip.breakdown?.map((item, idx) => (
                  <div
                    key={idx}
                    style={{
                      display: 'flex',
                      justifyContent: 'space-between',
                      padding: '0.5rem 0',
                      borderBottom: '1px solid var(--border-subtle)',
                      fontSize: '0.85rem',
                    }}
                  >
                    <span style={{ color: 'var(--text-muted)' }}>{item.category}</span>
                    <span style={{ fontWeight: 600, color: item.type === 'deduction' ? 'var(--danger)' : 'var(--text-main)' }}>
                      {item.type === 'deduction' ? '-' : '+'}{formatCurrency(item.amount)}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Total Net Salary */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem', backgroundColor: 'rgba(16, 185, 129, 0.1)', borderRadius: 'var(--radius-sm)', border: '1px solid rgba(16, 185, 129, 0.3)' }}>
              <span style={{ fontWeight: 600, color: '#e0e7ff' }}>Net Disbursed Amount</span>
              <span style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--success)' }}>
                {formatCurrency(selectedPayslip.net_salary)}
              </span>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '0.5rem' }}>
              <button
                onClick={() => handleDownload(selectedPayslip)}
                className="btn btn-primary"
                style={{ display: 'flex', gap: '0.5rem' }}
              >
                <Download size={16} /> Download Signed Payslip (PDF)
              </button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default EmployeePayroll;
